### ISSUE TITLE
Unable to update array of entities

### ISSUE THREAD

**Issue by Mika571** [Kinvey/js-sdk#222]
### Description
Unable to update an array of existing entities, I believe this might be a bug in the networkstore.js save method where passing in an array of entities won't be handled correctly.
```javascript
 save(entity, options) {
    if (entity._id) {
      return this.update(entity, options);
    }

    return this.create(entity, options);
  }
```
### Kinvey SDK Version
3.9.5

#### NodeJS version
v6.11.2

**Comment by Mika571** [comment]
Good point, thanks @thomasconner

**Comment by Mika571** [comment]
Just on this, what is the best way for saving an array of entities in a loop using a cache store? The issue I am having is that after the first iteration I get the following error as the datastore has not finished pushing the first entity to the backend:
 `SyncError: Data is already being pushed to the backend. Please wait for it to complete before pushing new data to the backend.` 
What is the best practice for doing this?

**Comment by georgiwe** [comment]
@Mika571 , your safest option is to make those requests sequential. We are planning, as part of a future release, to remove this particular limitation. You would then be able to make the requests in parallel.

**Comment by Mika571** [comment]
Thanks, @georgiwe is there a best practice for making promises synchronous?

**Comment by georgiwe** [comment]
By "synchronous" I assume you mean chaining them, so the requests are made sequentially. There is no best practice, enforced or recommended by us. Anything that works with promises, would work. Something like this:

```javascript
const store = Kinvey.DataStore.collection('collection-name', Kinvey.DataStoreType.Network);
const entities = [{ name: 'entity1' }, { name: 'entity2' }, { name: 'entity3' }];

const allRequestsDone = entities.reduce((entity, result) => {
  return result.then(() => store.create(entity));
}, Promise.resolve());

allRequestsDone.then(() => console.log('all entities created'));
```

Of course, error handling must be considered.

Let me know if I misunderstood your question. But in general, we don't have any specific recommendations when it comes to promises. It's just not possible to reliably do these requests in parallel, right now.
