### ISSUE TITLE
Number.isNaN is not available in IE11, but used in the sdk

### ISSUE THREAD

**Issue by boyandim** [Kinvey/js-sdk#239]
### Description 
According to the [Number.IsNaN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN) is not available for IE desktop browser except for Edge (IE11 does not support it for example). 

Currently it is used in the sdk [here ](https://github.com/Kinvey/js-sdk/blob/master/src/core/utils/object.js#L8). In my case it is trying to determine whether query.skip is number and it throws an error. 

There is an easy poly-fill provided in the MDN article or simply use the lodash method for checking if value is number. 

### Kinvey SDK Version
v 3.9.9	

#### NodeJS version
v 8.9.4

**Comment by thomasconner** [comment]
Thanks @boyandim. We will fix this issue for the next release.
