### ISSUE TITLE
Missing changelog and breaking changes summary

### ISSUE THREAD

**Issue by manoldonev** [Kinvey/js-sdk#466]
Can you add a CHANGELOG.md file to keep track of release history and document breaking changes -- see https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/CHANGELOG.md for example.

Currently I was trying to migrate some of the [NativeScript app templates](https://github.com/NativeScript/nativescript-app-templates/tree/master/packages/template-master-detail-kinvey) to latest Kinvey and it seems there are some breaking changes between 3.12.3 and 4.1.0 e.g.
```
JavaScript error:
file:///app/shared/kinvey.common.js:12:7: JS ERROR TypeError: undefined is not an object (evaluating 'Kinvey.init')
(CoreFoundation) *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: TypeError: undefined is not an object (evaluating 'Kinvey.init')
at
1   anonymous@file:///app/shared/kinvey.common.js:12:7
```

While I was able to solve this particular error, it would be good to have all the breaking changes summarized in one place in the changelog.

Thanks!

**Comment by thomasconner** [comment]
@manoldonev We have recently added support for [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/) that will help us to point out breaking changes and update our CHANGELOG more accurately.
